# Generated by Django 5.0.1 on 2024-03-17 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model Name')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Manufacturer')),
                ('uav_type', models.CharField(max_length=50, verbose_name='Type/Class')),
                ('weight', models.FloatField(verbose_name='Weight (kg)')),
                ('dimensions_length', models.FloatField(verbose_name='Length (m)')),
                ('dimensions_width', models.FloatField(verbose_name='Width (m)')),
                ('dimensions_height', models.FloatField(verbose_name='Height (m)')),
                ('max_speed', models.FloatField(verbose_name='Maximum Speed (km/h)')),
                ('range', models.FloatField(verbose_name='Range (km)')),
                ('endurance', models.FloatField(verbose_name='Endurance (hours)')),
                ('payload_capacity', models.FloatField(verbose_name='Payload Capacity (kg)')),
                ('communication_range', models.FloatField(verbose_name='Communication Range (km)')),
                ('navigation_system', models.CharField(max_length=100, verbose_name='Navigation System')),
                ('camera_imaging_system', models.CharField(max_length=100, verbose_name='Camera/Imaging System')),
                ('operating_altitude', models.FloatField(verbose_name='Operating Altitude (m)')),
                ('takeoff_landing_method', models.CharField(max_length=100, verbose_name='Takeoff/Landing Method')),
                ('control_interface', models.CharField(max_length=100, verbose_name='Control Interface')),
                ('special_features', models.TextField(verbose_name='Special Features')),
                ('rent_price_per_hour', models.FloatField(verbose_name='Rent Price Per Hour')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Company')),
            ],
            options={
                'verbose_name': 'UAV',
                'verbose_name_plural': 'UAVs',
            },
        ),
    ]
