# Generated by Django 5.0.1 on 2024-03-17 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentedUAVs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('uavs', models.ManyToManyField(related_name='rented_uavs', to='uav.uav')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_uavs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-startdate'],
            },
        ),
    ]
